### ISSUE TITLE
netbox2aquilon: Rollback on failure?

### ISSUE THREAD

**Issue by drossy** [stfc/Netbox-utils#18]
Currently on failure netbox2aquilon exits straight away, this potentially leaves the host in a half-created state, and will cause subsequent runs of the same netbox2aquilon run to fail. Should we consider rolling back what netbox2aquilon has done if it hits an error?

**Comment by jrha** [comment]
This is a really good idea, although we'd need to be careful to handle cases where a failure occurred due to an object already existing in aquilon…
